apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: dwight
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: scranton
          patternType: literal
          type: topic
      - host: '*'
        operation: Describe
        resource:
          name: scranton
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
