apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    authorization:
      type: simple
    config:
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: scram-sha-512
    replicas: 3
    storage:
      type: ephemeral
    version: 2.5.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
